### ISSUE TITLE
Current Weather

### ISSUE THREAD

**Issue by IB4650** [nat2001/makeceefax#1]
Hi Nathan,
  I would be very gratefull if you could provide a Current Weather forecast in makeceefax as
you did in makenews as it gives current barrometric preasure readings that I like to have included
in the weather forecast. Could you also inlude page numbers in the make Newsreel Module.

Best regards,
Ian.

**Comment by nat2001** [comment]
Hi, 
I'll write the current forecast asap.
> Could you also inlude page numbers in the make Newsreel


Do you want to change them? There's a file in the makenewsreel folder called pages.txt which contains all the pages to be put in the carousel if that's what you mean.

**Comment by IB4650** [comment]
Hi Nathan,
   On page numbers I mean to create number of pages like 1/12 at the top of the carousel and also include it in the Science and Technology pages.

Regards,
Ian.

**Comment by nat2001** [comment]
OK, that's something I've been meaning to fix so I'll get on with it

**Comment by nat2001** [comment]
Hi,
I've added subpage numbering on the Sci-tech news and the UK weather Outlook. However, I'm not sure about the newsreel. Due to it's flexible nature, the usual subpage number positions won't work on all subpages, and I'm unable to find an original Ceefax newsreel with this numbering

**Comment by IB4650** [comment]
Hi Nathan,
  I have been experimenting with the Newsreel module this morning by the
$ss=1 string and found the same problem but so far I had to print it consistently in line OL24 by removing the link pages to display page numbers. To give you some idea of my Ceefax setup, I use p100 template  from June, 1983, I use the news templates from Oct 1988 and my sports page templates from Dec 1995. By inserting my templates on makeceefax I get the authentic look that I like. I use makenewsreel to create P198 which used to be the old Ceefax Service page with News, Finance, Sport and Tv details. I get my preferred presentation pages from https://db.viewdata.org.uk.

Regards,
Ian.

**Comment by nat2001** [comment]
What I could do is add an option in makenewsreel's config file. It would allow you to turn subpage numbering on and off depending on your setup and decide what line it's on. I could also give the option to overwrite the entire line or just add the numbers at the end of the line leaving the rest intact.
On another note, last night I added the Current P404. I just added random places in the config file for testing, if you want to change them to more appropriate areas please do and share here!

**Comment by IB4650** [comment]
Good Evening,
  I would be very happy if you could include the numbered pages in the makenewsreel config file as an option. If it is able to overwrite in the top right hand corner of the teletext page which would be better if that can be achieved.

Regards,
Ian.

**Comment by nat2001** [comment]
The latest commit should do this. In the config file for makenewsreel is the constant "spnumbers". By default it is set to 'false' to disable it but you can add a line number and it will add the subpage numbers to this line.
"overwrite" toggles between writing the numbers over the end of the line or just blanking the line. (true or false)

**Comment by IB4650** [comment]
Good Morning Nathan,
  How do you get the observation Id array numbers to add new Towns and Cities to the Current Weather page and the 5 day forecast?

Regards,
Ian.

**Comment by nat2001** [comment]
Have a look here:
http://datapoint.metoffice.gov.uk/public/data/val/wxfcs/all/xml/sitelist?key={Your key}

**Comment by IB4650** [comment]
Hi Nathan,
  Thank you very much for the link I am now able to add more places to my Ceefax Weather pages.
I have recently adapted my version of makeceefax to have World news and home news made separate so I create a home section, an Irish news section and World news section.
 Regards,
Ian.

**Comment by nat2001** [comment]
No problem. If you've any other problems / suggestions don't hesitate to comment
